version: '4'

services:
  mongodbOrderService:
    image: mongo:latest
    container_name: mongodbOrderService
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: order-service
    volumes:
      - ./data:/data/db