version: '4'

services:
  mongodbPaymentService:
    image: mongo:latest
    container_name: mongodbPaymentService
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: payment-service
    volumes:
      - ./data:/data/db