version: '4'

services:
  mongodbOrderService:
    image: mongo:latest
    container_name: mongodbOrderService
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: order-service
    volumes:
      - ./data/orderService:/data/db

  mongodbInventoryService:
    image: mongo:latest
    container_name: mongodbInventoryService
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: inventory-service
    volumes:
      - ./data/inventoryService:/data/db

  mongodbPaymentService:
    image: mongo:latest
    container_name: mongodbPaymentService
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: payment-service
    volumes:
      - ./data/paymentService:/data/db